--- Makefile.linux_openmp_64	2019-03-08 22:08:10.000000000 +0000
+++ Makefile	2019-03-14 18:54:40.226801184 +0000
@@ -6,7 +6,7 @@
 USE_ZLIB = -DHAVE_ZLIB
 LZLIB    = -lz
 USE_GIFTI = -DHAVE_GIFTI
-LGIFTI    = /usr/lib64/libexpat.a
+LGIFTI    = /usr/lib/libexpat.so
 
 # ------------------------------
 # python from C (off for now)
@@ -17,7 +17,7 @@
 # X configuration
 #
 # uncomment to build using local /usr/local/afniX 'X' tree
-USE_LOCAL_X_TREE = 1
+# USE_LOCAL_X_TREE = 1
 ifdef USE_LOCAL_X_TREE
     XROOT = /usr/local/afniX
     XROOT_I = -I$(XROOT)/include
@@ -26,7 +26,7 @@
 endif
 
 # uncomment USE_LESSTIF to use lesstif instead of openmotif
-# USE_LESSTIF = 1
+USE_LESSTIF = 1
 ifdef USE_LESSTIF
     LESSTIF_DEFS = -DUSING_LESSTIF
 
@@ -37,7 +37,7 @@
 endif
 
 # in case user wants to override with system dynamic libs
-# XLIBS = -lXm -lXt
+XLIBS = -lXm -lXt
 # ----------------------------------------------------------------------
 
 CCDEBS = -DAFNI_DEBUG -DIMSEQ_DEBUG -DDISPLAY_DEBUG -DTHD_DEBUG
@@ -46,7 +46,8 @@
 CC     = /usr/bin/gcc -O2 -m64 -fPIC -DREAD_WRITE_64 -DLINUX2 $(CEXTRA)
 CCVOL  = /usr/bin/gcc -O2 -m64 -fPIC -DREAD_WRITE_64 -DLINUX2 $(CEXTRA)
 CCFAST = /usr/bin/gcc -O2 -m64 -fPIC -DREAD_WRITE_64 -DLINUX2 $(CEXTRA)
-CCOLD  = /usr/bin/gcc -V 34 -O2 -m64 -fPIC -DREAD_WRITE_64 -DLINUX2 $(CEXTRA)
+#CCOLD  = /usr/bin/gcc -V 34 -O2 -m64 -fPIC -DREAD_WRITE_64 -DLINUX2 $(CEXTRA)
+CCOLD  = $(CCFAST)
 
 # The following line includes compiling for the SSE operations.
 # However, I found that it actually makes things worse in some test code.
